### ISSUE TITLE
Overridden HTTP differs from specs: Missing boolean return.

### ISSUE THREAD

**Issue by Grocel** [CFC-Servers/cfc_cl_http_whitelist#46]
The implementation is differing from the original with the potential of breaking other code, e.g. addons.
As stated in [Global.HTTP](https://wiki.facepunch.com/gmod/Global.HTTP) the `HTTP()` function returns a boolean. At the moment the overridden function always returns nothing (nil).

https://github.com/CFC-Servers/cfc_cl_http_whitelist/blob/265ce54eea0f386c6eb0390fe31f329f905b9d1f/lua/cfc_http_restrictions/wraps/http.lua#L5-L24

Additional remarks:
- You might want to check if `http.Post` and `http.Fetch` are in specs too.

**Comment by plally** [comment]
Thanks, ill get a fix for that.

The additional remark shouldn't be an issue because http.Post and http.Fetch are no longer wrapped directly
